# Generated by Django 3.1.4 on 2021-01-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ninja_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
